#!/usr/bin/env bash
# Beat: "tuppence reconciles from a pinned, signed GitRepository, healthily, and carries its risk skin (toward-strict)."
# Run after scripts/up.sh. Three outcomes only:
#   PASS (exit 0)  every assertion observed true
#   FAIL (exit 1)  an assertion observed false
#   SKIP (exit 3)  could not look: no docker, no kind cluster, Flux not Ready
source "$(dirname "${BASH_SOURCE[0]}")/scripts/lib.sh"
need_substrate

fail() { echo "FAIL: $*" >&2; exit 1; }
ready() { # kind/name/ns -> asserts Ready=True
  local got
  got=$(live "$3" "$1" "$2" '{.status.conditions[?(@.type=="Ready")].status}')
  [ "$got" = True ] || fail "$1/$2 Ready=$got (want True)"
}
live() { kubectl --context "$CTX" --request-timeout=20s -n "$1" get "$2" "$3" -o "jsonpath=$4" 2>/dev/null; }
want() { [ "$1" = "$2" ] || fail "$3: live '$1', expected '$2' (from $EXPECT_FROM)"; }

# Expected values are READ, never hardcoded -- but from WHICH world? Two exist
# and they do not share a commit:
#   * the real remote (a github.com url): the pins are the checked-in gitops/
#     tree, and the reconciled content is the tree AT the pinned tag -- a tag
#     cannot carry its own commit, so the working tree is not what the cluster
#     reconciles.
#   * the offline touring demo (the in-cluster git-server url): scripts/up.sh
#     seeds a throwaway repo from the WORKING gitops/ tree on every run, so its
#     commit is a brand-new sha each run and can never equal the remote pin.
#     The pins are then what that same run recorded in .work/seeded-pin.yaml,
#     and the reconciled content is the working gitops/apps tree.
# The LIVE url picks the world, so this never guesses. Either way a live
# revision that is not the expected one is a FAIL -- never a pass, never a skip.
# Shape chosen over making the seed byte-reproducible and committing its sha:
# half the seed is the sibling nist repo's tree, which this repo does not own
# and could not honestly pin, and every gitops/ edit would need a hash
# regenerated by hand. ponytail: if the seed ever becomes reproducible, delete
# seeded-pin.yaml and compare against a committed sha instead.
field() { sed -n "s/^ *$1: *\"\{0,1\}\([^\" #]*\)\"\{0,1\}.*/\1/p" | sed 1q; }
pin()   { field "$2" < "$GITOPS_DIR/flux-system/$1"; }
SEEDED="$WORK/seeded-pin.yaml"
LIVE_URL=$(live flux-system gitrepository "$CLUSTER" '{.spec.url}')
[ -n "$LIVE_URL" ] || fail "no GitRepository '$CLUSTER' in flux-system on $CTX -- run scripts/up.sh"
case "$LIVE_URL" in
  *git-server.flux-system.svc.cluster.local*)
    [ -f "$SEEDED" ] || skip "GitRepository '$CLUSTER' points at the in-cluster git server ($LIVE_URL), i.e. the offline demo, but $SEEDED does not exist: scripts/up.sh has not run here (or .work was cleared), so there is no record of what was seeded to check the cluster against"
    EXPECT_FROM="the offline seed scripts/up.sh recorded in .work/seeded-pin.yaml"
    SELF_URL=$(field url < "$SEEDED")
    SELF_TAG=$(field tag < "$SEEDED");        SELF_COMMIT=$(field commit < "$SEEDED")
    NIST_URL=$(field nist_url < "$SEEDED")
    NIST_TAG=$(field nist_tag < "$SEEDED");   NIST_COMMIT=$(field nist_commit < "$SEEDED")
    [ -n "$SELF_COMMIT" ] && [ -n "$NIST_COMMIT" ] || fail "$SEEDED carries no commit/nist_commit -- re-run scripts/up.sh"
    TREE="working gitops/apps tree, which is what up.sh seeded"
    at_pin() { cat "$GITOPS_DIR/apps/$1"; }
    ;;
  *)
    EXPECT_FROM="the checked-in gitops/ tree"
    SELF_URL=$(pin gotk-sync.yaml url)
    SELF_TAG=$(pin gotk-sync.yaml tag);       SELF_COMMIT=$(pin gotk-sync.yaml commit)
    NIST_URL=$(pin gotk-sync-nist.yaml url)
    NIST_TAG=$(pin gotk-sync-nist.yaml tag);  NIST_COMMIT=$(pin gotk-sync-nist.yaml commit)
    TREE="tree at $SELF_TAG"
    at_pin() { git -C "$HERE" show "$SELF_TAG:gitops/apps/$1" 2>/dev/null || fail "tag $SELF_TAG (the self-pin) is not in this clone; fetch tags"; }
    ;;
esac
PLATFORM_TAG=$(field tag < "$GITOPS_DIR/platform/platform-pin.yaml")
PLATFORM_COMMIT=$(field commit < "$GITOPS_DIR/platform/platform-pin.yaml")
WANT_VERSION=$(at_pin version-configmap.yaml | field policyVersion)
WANT_CATALOG=$(at_pin nist-pin-configmap.yaml | field catalogVersion)
[ -n "$SELF_TAG$NIST_TAG$WANT_VERSION$WANT_CATALOG" ] || fail "could not read the pins from $EXPECT_FROM"

say "1. GitRepository is Ready and pinned to $SELF_TAG @ ${SELF_COMMIT:-<no commit pinned in gotk-sync.yaml>} (expected pins from $EXPECT_FROM)"
ready gitrepository tuppence flux-system
want "$LIVE_URL" "$SELF_URL" "GitRepository url"
want "$(live flux-system gitrepository tuppence '{.spec.ref.tag}')" "$SELF_TAG" "GitRepository tag"
c=$(live flux-system gitrepository tuppence '{.spec.ref.commit}')
grep -qE '^[0-9a-f]{40}$' <<<"$c" || fail "GitRepository commit not pinned (got '$c')"
[ -z "$SELF_COMMIT" ] || want "$c" "$SELF_COMMIT" "GitRepository commit"

say "2. Kustomization is Ready (reconcile healthy)"
ready kustomization tuppence flux-system

say "3. the reconciled content actually landed in the cluster ($TREE)"
kubectl --context "$CTX" --request-timeout=20s get ns tuppence >/dev/null 2>&1 || fail "namespace 'tuppence' not reconciled"
want "$(live tuppence cm tuppence-live-version '{.data.policyVersion}')" "$WANT_VERSION" "live version configmap"

say "4. the pinned nist (regulator) dependency reconciled healthy at $NIST_TAG @ $NIST_COMMIT"
ready gitrepository nist flux-system
want "$(live flux-system gitrepository nist '{.spec.url}')" "$NIST_URL" "nist GitRepository url"
want "$(live flux-system gitrepository nist '{.spec.ref.tag}')" "$NIST_TAG" "nist GitRepository tag"
want "$(live flux-system gitrepository nist '{.spec.ref.commit}')" "$NIST_COMMIT" "nist GitRepository commit"
want "$(live tuppence cm tuppence-nist-pin '{.data.catalogVersion}')" "$WANT_CATALOG" "nist-pin configmap"

say "5. the platform pin (opt-in) matches gitops/platform/platform-pin.yaml when applied"
if live flux-system gitrepository platform '{.metadata.name}' | grep -qx platform; then
  want "$(live flux-system gitrepository platform '{.spec.ref.tag}')" "$PLATFORM_TAG" "platform GitRepository tag"
  want "$(live flux-system gitrepository platform '{.spec.ref.commit}')" "$PLATFORM_COMMIT" "platform GitRepository commit"
else
  echo "   platform GitRepository not applied on $CTX (opt-in, see platform-pin.yaml); nothing to compare"
fi

say "6. the risk-appetite skin reconciled ($TREE)"
tol=$(live tuppence cm tuppence-risk-appetite '{.data.toleranceGBP}')
want "$tol" "$(at_pin risk-appetite-configmap.yaml | field toleranceGBP)" "risk-appetite configmap tolerance"
# The appetite is a signed fact on this org's OWN party.yaml (ADR-0021); the
# platform's risk/appetite.json fixture is retired. No `if [ -f ]` guard: the
# party artefact always exists here, so this check can never silently skip.
want_tol=$(python3 -c "import yaml; print(yaml.safe_load(open('$HERE/party.yaml'))['appetite']['tolerance']['amount'])")
want "$tol" "$want_tol" "risk-appetite configmap drifted from tuppence's own signed party.yaml appetite"
echo "PASS: tuppence reconciles from a pinned GitRepository ($SELF_TAG), healthy, content live, nist dependency pinned ($NIST_TAG), risk skin (toward-strict) live."
