#!/usr/bin/env bash
# Beat: "tuppence reconciles from a pinned, signed GitRepository, healthily, and carries its risk skin (toward-strict)."
# Run after scripts/up.sh. Three outcomes only:
#   PASS (exit 0)  every assertion observed true
#   FAIL (exit 1)  an assertion observed false
#   SKIP (exit 3)  could not look: no docker, no kind cluster, Flux not Ready
source "$(dirname "${BASH_SOURCE[0]}")/scripts/lib.sh"

# --- the five-fact sample grades FIRST, cluster-free (ecosystem ticket 60) -------------------
# The sample is taken by .github/workflows/drift-sample.yml on the observation lane and graded
# from drift/samples.jsonl; no cluster is needed to READ it. This grading used to sit at the
# end of this file, BELOW need_substrate, so the citable run (no kind in CI) exited 3 before
# ever reading the lane -- the gate could not consume the conversion machinery
# (REVIEW-2026-08-31, M7). So it grades first:
#   a lane fact observed false     -> FAIL now, cluster or no cluster;
#   sample PASS, no local cluster  -> PASS on the sample alone: the local touring cluster is a
#     seeded rehearsal world, and the sample observes a cluster reconciling the REAL remotes,
#     which is the stronger claim;
#   no gradable sample, no cluster -> SKIP carrying both reasons.
# A local cluster that EXISTS keeps the old behaviour in full: every live assertion below runs.
SAMPLE_RC=3
SAMPLE_OUT="SKIP: python3 here has no pyyaml, so drift/five-facts.py cannot read the pins or the pre-registration"
if python3 -c 'import yaml' 2>/dev/null; then
  set +e
  SAMPLE_OUT="$(python3 "$(dirname "${BASH_SOURCE[0]}")/drift/five-facts.py" grade --max-age-hours "${FIVE_FACT_MAX_AGE_HOURS:-48}" 2>&1)"; SAMPLE_RC=$?
  set -e
fi
say "0. the five-fact sample: the composed set in force, from signed sources (graded first, cluster-free)"
printf '%s\n' "$SAMPLE_OUT" | sed 's/^/   /'
if [ "$SAMPLE_RC" != 0 ] && [ "$SAMPLE_RC" != 3 ]; then
  echo "FAIL: $(printf '%s\n' "$SAMPLE_OUT" | tail -1)" >&2; exit 1
fi

# --- the local cluster, when there is one ----------------------------------------------------
if ! { have docker && have kind && have kubectl && docker info >/dev/null 2>&1 \
       && kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; }; then
  if [ "$SAMPLE_RC" = 0 ]; then
    echo "PASS: no local kind cluster '$CLUSTER' here, and none is needed: the latest lane sample observes the composed set in force from signed sources on a cluster reconciling the real remotes."
    exit 0
  fi
  skip "no local kind cluster '$CLUSTER' to observe here, and the lane sample cannot stand in: $(printf '%s\n' "$SAMPLE_OUT" | sed -n 's/^SKIP: //p' | tail -1)"
fi
need_substrate


fail() { echo "FAIL: $*" >&2; exit 1; }
ready() { # kind/name/ns -> asserts Ready=True
  local got
  got=$(live "$3" "$1" "$2" '{.status.conditions[?(@.type=="Ready")].status}')
  [ "$got" = True ] || fail "$1/$2 Ready=$got (want True)"
}
live() { kubectl --context "$CTX" --request-timeout=20s -n "$1" get "$2" "$3" -o "jsonpath=$4" 2>/dev/null; }
want() { [ "$1" = "$2" ] || fail "$3: live '$1', expected '$2' (from $EXPECT_FROM)"; }

# Expected values are READ, never hardcoded -- but from WHICH world? Two exist
# and they do not share a commit:
#   * the real remote (a github.com url): the pins are the checked-in gitops/
#     tree, and the reconciled content is the tree AT the pinned tag -- a tag
#     cannot carry its own commit, so the working tree is not what the cluster
#     reconciles.
#   * the offline touring demo (the in-cluster git-server url): scripts/up.sh
#     seeds a throwaway repo from the WORKING gitops/ tree on every run, so its
#     commit is a brand-new sha each run and can never equal the remote pin.
#     The pins are then what that same run recorded in .work/seeded-pin.yaml,
#     and the reconciled content is the working gitops/apps tree.
# The LIVE url picks the world, so this never guesses. Either way a live
# revision that is not the expected one is a FAIL -- never a pass, never a skip.
# Shape chosen over making the seed byte-reproducible and committing its sha:
# half the seed is the sibling nist repo's tree, which this repo does not own
# and could not honestly pin, and every gitops/ edit would need a hash
# regenerated by hand. ponytail: if the seed ever becomes reproducible, delete
# seeded-pin.yaml and compare against a committed sha instead.
field() { sed -n "s/^ *$1: *\"\{0,1\}\([^\" #]*\)\"\{0,1\}.*/\1/p" | sed 1q; }
pin()   { field "$2" < "$GITOPS_DIR/flux-system/$1"; }
SEEDED="$WORK/seeded-pin.yaml"
LIVE_URL=$(live flux-system gitrepository "$CLUSTER" '{.spec.url}')
[ -n "$LIVE_URL" ] || fail "no GitRepository '$CLUSTER' in flux-system on $CTX -- run scripts/up.sh"
case "$LIVE_URL" in
  *git-server.flux-system.svc.cluster.local*)
    [ -f "$SEEDED" ] || skip "GitRepository '$CLUSTER' points at the in-cluster git server ($LIVE_URL), i.e. the offline demo, but $SEEDED does not exist: scripts/up.sh has not run here (or .work was cleared), so there is no record of what was seeded to check the cluster against"
    EXPECT_FROM="the offline seed scripts/up.sh recorded in .work/seeded-pin.yaml"
    SELF_URL=$(field url < "$SEEDED")
    SELF_TAG=$(field tag < "$SEEDED");        SELF_COMMIT=$(field commit < "$SEEDED")
    NIST_URL=$(field nist_url < "$SEEDED")
    NIST_TAG=$(field nist_tag < "$SEEDED");   NIST_COMMIT=$(field nist_commit < "$SEEDED")
    [ -n "$SELF_COMMIT" ] && [ -n "$NIST_COMMIT" ] || fail "$SEEDED carries no commit/nist_commit -- re-run scripts/up.sh"
    TREE="working gitops/apps tree, which is what up.sh seeded"
    at_pin() { cat "$GITOPS_DIR/apps/$1"; }
    ;;
  *)
    EXPECT_FROM="the checked-in gitops/ tree"
    SELF_URL=$(pin gotk-sync.yaml url)
    SELF_TAG=$(pin gotk-sync.yaml tag);       SELF_COMMIT=$(pin gotk-sync.yaml commit)
    NIST_URL=$(pin gotk-sync-nist.yaml url)
    NIST_TAG=$(pin gotk-sync-nist.yaml tag);  NIST_COMMIT=$(pin gotk-sync-nist.yaml commit)
    TREE="tree at $SELF_TAG"
    at_pin() { git -C "$HERE" show "$SELF_TAG:gitops/apps/$1" 2>/dev/null || fail "tag $SELF_TAG (the self-pin) is not in this clone; fetch tags"; }
    ;;
esac
PLATFORM_TAG=$(field tag < "$GITOPS_DIR/platform/platform-pin.yaml")
PLATFORM_COMMIT=$(field commit < "$GITOPS_DIR/platform/platform-pin.yaml")
WANT_VERSION=$(at_pin version-configmap.yaml | field policyVersion)
WANT_CATALOG=$(at_pin nist-pin-configmap.yaml | field catalogVersion)
[ -n "$SELF_TAG$NIST_TAG$WANT_VERSION$WANT_CATALOG" ] || fail "could not read the pins from $EXPECT_FROM"

say "1. GitRepository is Ready and pinned to $SELF_TAG @ ${SELF_COMMIT:-<no commit pinned in gotk-sync.yaml>} (expected pins from $EXPECT_FROM)"
ready gitrepository tuppence flux-system
want "$LIVE_URL" "$SELF_URL" "GitRepository url"
want "$(live flux-system gitrepository tuppence '{.spec.ref.tag}')" "$SELF_TAG" "GitRepository tag"
c=$(live flux-system gitrepository tuppence '{.spec.ref.commit}')
grep -qE '^[0-9a-f]{40}$' <<<"$c" || fail "GitRepository commit not pinned (got '$c')"
[ -z "$SELF_COMMIT" ] || want "$c" "$SELF_COMMIT" "GitRepository commit"

say "2. Kustomization is Ready (reconcile healthy)"
ready kustomization tuppence flux-system

say "3. the reconciled content actually landed in the cluster ($TREE)"
kubectl --context "$CTX" --request-timeout=20s get ns tuppence >/dev/null 2>&1 || fail "namespace 'tuppence' not reconciled"
want "$(live tuppence cm tuppence-live-version '{.data.policyVersion}')" "$WANT_VERSION" "live version configmap"

say "4. the pinned nist (regulator) dependency reconciled healthy at $NIST_TAG @ $NIST_COMMIT"
ready gitrepository nist flux-system
want "$(live flux-system gitrepository nist '{.spec.url}')" "$NIST_URL" "nist GitRepository url"
want "$(live flux-system gitrepository nist '{.spec.ref.tag}')" "$NIST_TAG" "nist GitRepository tag"
want "$(live flux-system gitrepository nist '{.spec.ref.commit}')" "$NIST_COMMIT" "nist GitRepository commit"
want "$(live tuppence cm tuppence-nist-pin '{.data.catalogVersion}')" "$WANT_CATALOG" "nist-pin configmap"

say "5. the platform pin (opt-in) matches gitops/platform/platform-pin.yaml when applied"
if live flux-system gitrepository platform '{.metadata.name}' | grep -qx platform; then
  want "$(live flux-system gitrepository platform '{.spec.ref.tag}')" "$PLATFORM_TAG" "platform GitRepository tag"
  want "$(live flux-system gitrepository platform '{.spec.ref.commit}')" "$PLATFORM_COMMIT" "platform GitRepository commit"
else
  echo "   platform GitRepository not applied on $CTX (opt-in, see platform-pin.yaml); nothing to compare"
fi

say "6. the risk-appetite skin reconciled ($TREE)"
tol=$(live tuppence cm tuppence-risk-appetite '{.data.toleranceGBP}')
want "$tol" "$(at_pin risk-appetite-configmap.yaml | field toleranceGBP)" "risk-appetite configmap tolerance"
# The appetite is a signed fact on this org's OWN party.yaml (ADR-0021); the
# platform's risk/appetite.json fixture is retired. No `if [ -f ]` guard: the
# party artefact always exists here, so this check can never silently skip.
want_tol=$(python3 -c "import yaml; print(yaml.safe_load(open('$HERE/party.yaml'))['appetite']['tolerance']['amount'])")
want "$tol" "$want_tol" "risk-appetite configmap drifted from tuppence's own signed party.yaml appetite"
echo "   reconcile assertions 1-6 all observed true: tuppence reconciles from a pinned GitRepository ($SELF_TAG), healthy, content live, nist dependency pinned ($NIST_TAG), risk skin (toward-strict) live."

say "6b. the composed cage is actually enforced on $CTX (a governed Namespace that declares a tier)"
# 2026-08-29 review: this file asserted a healthy reconcile on a cluster with no
# Kyverno at all. tuppence's Namespace carries policy-as-versioned.dev/governed=true
# and posture.acme.io/tier, and a pod with no claim, hostNetwork and privileged
# was admitted untouched -- the manifest was inert and nothing here said so.
# Silence about a cage that is not there is the shape the brief forbids.
if ! timeout 10 kubectl --context "$CTX" get crd mutatingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  skip "Kyverno MutatingPolicy CRD not installed on $CTX, so the composed cage is not enforced there at all: the governed Namespace declares a tier that nothing reads, and no pod in it is caged. Run platform/engine/up.sh then platform/graded/up.sh against this cluster (as driftwood has)"
fi
for pol in $(python3 -c "
import pathlib, sys
d = pathlib.Path('$HERE/composed/policies')
print(' '.join(sorted(p.name[1:].replace('.', '-') for p in d.iterdir() if p.is_dir())) if d.is_dir() else '')
"); do
  timeout 10 kubectl --context "$CTX" get mutatingpolicy "cage-tier-$pol" >/dev/null 2>&1 \
    || skip "composed/policies/v${pol//-/.} is rendered here but its cage-tier MutatingPolicy is not installed on $CTX; the tier this Namespace declares is enforced by nothing"
done
echo "   the cage this repo composes is installed on $CTX"

# --- 7. the five-fact sample (ecosystem ticket 42, widening ticket 40) --------
# Everything above proves the RECONCILE is healthy against whichever world the live url picks.
# It does not prove the thing ticket 16 Q1 asks for: that tuppence's COMPOSED POLICY SET is in
# force, from sources whose signed tags were verified at the source boundary, on a cluster that
# reconciles from the publishers' REAL remotes. That is five facts per source, and one sample of
# a cluster cannot be taken by this script and then graded by it -- a presenter-run number is a
# rehearsal (ADR-0023, D4). The number comes from .github/workflows/drift-sample.yml, which
# brings up an ephemeral KinD in Actions, reconciles from the real remotes and APPENDS one record
# per source to drift/samples.jsonl. That append is an observation, which a clock may make (D1).
#
# So this section GRADES THE LATEST SAMPLE and nothing else:
#   no fresh sample            -> exit 3, could not look. Never a pass.
#   a fact observed false      -> exit 1.
#   all five true, every source, no falsifier fired -> exit 0.
# `five-facts.py grade` also refuses to grade anything PASS unless drift/window.yaml still
# declares all three falsifiers (ticket 40's rule that a sample passing with a falsifier
# undeclared is a fail), AND unless the newest sample is attributable to the observation lane --
# an Actions run id and a signed lane commit, so three lines typed into samples.jsonl by hand
# cannot grade PASS.
say "7. the five-fact sample verdict (graded above, before the substrate gate)"
py_done=graded-above
case "$SAMPLE_RC" in
  0) echo "PASS: the reconcile is healthy AND the latest five-fact sample observes the composed set in force from signed sources.";;
  *) skip "$(printf '%s\n' "$SAMPLE_OUT" | sed -n 's/^SKIP: //p' | tail -1)";;
esac
