apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: stamp-posture-2-0-1
  labels:
    app.kubernetes.io/part-of: platform
    policy-as-versioned.dev/policy: posture
    policy-as-versioned.dev/policy-version: 2.0.1
    policy-as-versioned.dev/composed-for: tuppence
  annotations:
    policy-as-versioned.dev/inherited-from: platform@1.1.1
    policy-as-versioned.dev/source-path: distribution/policies/v2.0.1/stamp-posture.yaml
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  matchConditions:
  - name: claims-a-policy-version
    expression: object.metadata.?labels['policy-as-versioned.dev/policy-version'].orValue('') != ''
  - name: only-this-policy-version
    expression: object.metadata.?labels['policy-as-versioned.dev/policy-version'].orValue('') == '2.0.1'
  mutations:
  - patchType: ApplyConfiguration
    applyConfiguration:
      expression: "Object{\n  metadata: Object.metadata{\n    labels: {\"posture.acme.io/version\": object.metadata.labels['policy-as-versioned.dev/policy-version']}\n  }\n}"
