apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: require-nonroot-4-0-0
  labels:
    app.kubernetes.io/part-of: platform
    policy-as-versioned.dev/policy: require-nonroot
    policy-as-versioned.dev/policy-version: 4.0.0
    policy-as-versioned.dev/composed-for: tuppence
  annotations:
    policy-as-versioned.dev/inherited-from: platform@2.0.1
    policy-as-versioned.dev/source-path: distribution/policies/v4.0.0/require-nonroot.yaml
spec:
  validationActions:
  - Audit
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  matchConditions:
  - name: only-this-policy-version
    expression: object.metadata.?labels['policy-as-versioned.dev/policy-version'].orValue('') == '4.0.0'
  validations:
  - expression: object.spec.?securityContext.?runAsNonRoot.orValue(false) == true
    message: pods on policy-version 4.0.0 must set spec.securityContext.runAsNonRoot=true
  - expression: object.spec.containers.all(c, c.?securityContext.?readOnlyRootFilesystem.orValue(false) == true)
    message: pods on policy-version 4.0.0 must set readOnlyRootFilesystem=true on every container
